using UnityEngine;
using static LGeom;
using System.Collections.Generic;

public class Turtle : MonoBehaviour
{
    // Attributes that change the way the tree is generated
    public float moveDistance = 1f; 
    public float cylinderRadius = 0.01f;
    public float rotateAngle = 45;

    public Material material;
    private bool color = true;
    private int currentSymbolIndex = 0;

    // The LSystem being interpretted
    public LSystem system;

    public List<GameObject> cylinders = new List<GameObject>();
    // To handle brackets in string
    private Stack<Vector3> positionStack = new Stack<Vector3>();
    private Stack<Quaternion> rotationStack = new Stack<Quaternion>();

    /// <summary>
    /// Loads the given system into the turtle that will be interpretted.
    /// </summary>
    /// <param name="system">LSystem that holds the generated symbol list to interpret.</param>
    public void loadSystem(LSystem system)
    {  
        deleteCylinders();
        currentSymbolIndex = 0;
        color = true;
        this.system = system;
    }

    /// <summary>
    /// Interpret the whole LSystem as it is in the LSystem.currentString.
    /// </summary>
    public void interpretFullSystem()
    {
        while (interpretNextSymbol());
    }

    /// <summary>
    /// Interpret the next symbol in the LSystem.currentString. Taking the current position from
    /// the currentSymbolIndex and updating it to maintain state. When the last symbol has been 
    /// interpretted this method will do nothing and return false. 
    /// This is where the alphabet for the LSystems is defined.
    /// </summary>
    /// <returns>true if there is another symbol to interpret, false if it is done.</returns>
    public bool interpretNextSymbol()
    {
        // Do not interpret if the turtle is at the end of the string
        if (currentSymbolIndex >= system.currentString.Count) {
            return false;
        }

        // Handle the different symbols in the alphabet
        Symbol s = system.currentString[currentSymbolIndex];
        switch (s.symbol)
        {
            case 'F':
                // Save the position before we move the turtle
                Transform oldTransform = transform;
                
                // Set the material for the cylinders.
                Material m = color ? material : null;
                // color = !color; // This allows alternating colors for debugging.

                // Generate the cylinder along the path
                cylinders.Add(LGeom.Cylinder(
                    oldTransform.position,
                    oldTransform.position + (transform.up*moveDistance),
                    cylinderRadius,
                    m
                )); 

                // Move the turtle along the path
                transform.position = oldTransform.position + (transform.up*moveDistance);
                break;
            case '+':
                // Rotate the turtle by the angle
                transform.Rotate(new Vector3(0,0,rotateAngle));
                break;
            case '-':
                // Rotate the turtle by the angle
                transform.Rotate(new Vector3(0,0,-rotateAngle));
                break;
            case '[':
                // Push the turtles current position and rotation to the stack
                positionStack.Push(transform.position);
                rotationStack.Push(transform.rotation);
                break;
            case ']':
                // Return the turtle the the top position and rotation on the stack
                transform.position = positionStack.Pop();
                transform.rotation = rotationStack.Pop();
                break;
            case 'X':
                // Do nothing on X, could omit
                break;
        }
        currentSymbolIndex++;
        return true;
    }

    /// <summary>
    /// Deletes all the cylinders that were generated by the turtle.
    /// </summary>
    public void deleteCylinders()
    {
        foreach (GameObject cylinder in cylinders)
        {
            Destroy(cylinder);
        }
        cylinders = new List<GameObject>();
    }
}
